version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: America/Los_Angeles
    open-pull-requests-limit: 5
    groups:
      development-dependencies:
        dependency-type: development
    commit-message:
      prefix: deps

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:30'
      timezone: America/Los_Angeles
    open-pull-requests-limit: 3
    groups:
      actions:
        patterns:
          - '*'
    commit-message:
      prefix: ci
